@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Event",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1077334738 { 
   	label=TimeInterval
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   TimeInterval1077334738[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TimeInterval</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ TimeInterval(start: LocalTime, end: LocalTime)</TD></TR>
<TR><TD ALIGN="LEFT" >+ fromScanner(scanner: Scanner): TimeInterval</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEnd(): LocalTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ getStart(): LocalTime</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2018976346 { 
   	label=MyCalender
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   MyCalender2018976346[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MyCalender</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   eventsOneTime: ArrayList&lt;Event&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   eventsRecurring: ArrayList&lt;Event&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># MyCalender()</TD></TR>
<TR><TD ALIGN="LEFT" >+ addEvent(event: Event): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ dump(fileWriter: FileWriter)</TD></TR>
<TR><TD ALIGN="LEFT" >- filterEventsOnDay(stream: Stream&lt;Event&gt;, date: LocalDate): ArrayList&lt;Event&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findConflicts(event: Event): List&lt;Event&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findRecurringEventByName(name: String): Event</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllEventsOnDate(date: LocalDate): ArrayList&lt;Event&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEventsOneTime(): ArrayList&lt;Event&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEventsRecurring(): ArrayList&lt;Event&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getOneTimeEventsOnDate(date: LocalDate): ArrayList&lt;Event&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ load(file: File)</TD></TR>
<TR><TD ALIGN="LEFT" >- printCalendar(selectedDays: ArrayList&lt;Integer&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >- printCalendar(now: YearMonth, selectedDays: ArrayList&lt;Integer&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printDayView(date: LocalDate)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printDayView(date: LocalDate, events: ArrayList&lt;Event&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printMonthView(month: YearMonth)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printMonthView()</TD></TR>
<TR><TD ALIGN="LEFT" >+ printTodayCalendar()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeEvent(event: Event): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_635062501 { 
   	label=Interval
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Interval635062501[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Interval&lt;T extends Comparable&lt;? super T&gt;&gt;</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   end: T [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   start: T [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ Interval(start: T, end: T)</TD></TR>
<TR><TD ALIGN="LEFT" ># getEnd(): T</TD></TR>
<TR><TD ALIGN="LEFT" ># getStart(): T</TD></TR>
<TR><TD ALIGN="LEFT" >+ overlaps(interval: Interval&lt;T&gt;): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_66816 { 
   	label=CLI
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CLI66816[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CLI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   calender: MyCalender [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prompt: Prompt [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   scanner: Scanner [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># CLI(scanner: Scanner)</TD></TR>
<TR><TD ALIGN="LEFT" >- dumpToFile(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- loadFromFile(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ mainLoop()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenCreate()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenDelete()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenDeleteAllOnDay()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenDeleteInteractive()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenDeleteRecurringEvent()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenEventList()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenGoTo()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenMainMenuLoop()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenViewBy()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenViewByDay()</TD></TR>
<TR><TD ALIGN="LEFT" >- screenViewByMonth()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_67338874 { 
   	label=Event
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Event67338874[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Event</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dateInterval: DateInterval [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   recurring: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repeatedDays: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timeInterval: TimeInterval [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># Event(name: String, date: LocalDate, timeInterval: TimeInterval)</TD></TR>
<TR><TD ALIGN="LEFT" ># Event(name: String, dateInterval: DateInterval, repeatedDays: int, timeInterval: TimeInterval)</TD></TR>
<TR><TD ALIGN="LEFT" >+ conflicts(event: Event): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ daysOfTheMonth(month: YearMonth): ArrayList&lt;Integer&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ fromScanner(scanner: Scanner): Event</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEndDate(): LocalDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEndTime(): LocalTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ getName(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getStartDate(): LocalDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ getStartTime(): LocalTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ isOnDay(date: LocalDate): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ isRecurring(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- repeatedDaysFromString(serialized: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >- repeatedDaysToString(unserialized: int): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ repeatedDaysToStringPadded(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_872874317 { 
   	label=DateInterval
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DateInterval872874317[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DateInterval</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ DateInterval(start: LocalDate, end: LocalDate)</TD></TR>
<TR><TD ALIGN="LEFT" >+ contains(month: YearMonth): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ contains(date: LocalDate): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ fromScanner(scanner: Scanner): DateInterval</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEnd(): LocalDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ getStart(): LocalDate</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
CLI66816 -> MyCalender2018976346[label="calender
[0..1]"];
Event67338874 -> DateInterval872874317[label="dateInterval
[0..1]"];
Event67338874 -> TimeInterval1077334738[label="timeInterval
[0..1]"];
Interval635062501 -> DateInterval872874317[arrowhead=none, arrowtail=empty, dir=both];
Interval635062501 -> TimeInterval1077334738[arrowhead=none, arrowtail=empty, dir=both];
MyCalender2018976346 -> Event67338874[label="eventsOneTime
[0..*]"];
MyCalender2018976346 -> Event67338874[label="eventsRecurring
[0..*]"];
    
}
@enduml